spring.application.name=Event_Booking_system
spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker?createDatabaseIfNotExist=true
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
